name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test action
        uses: ./
        id: test
        with:
          config: |
            matrix:
              arch: [manylinux1-x64,manylinux1-x86]
              py2: ["27","35","36","37","38","39"]
            operations:
              - type: append
                matrix:
                  arch: [manylinux2014-x64,manylinux2014-x86]
                  py2: ["310"]
              - type: append
                matrix:
                  arch: [manylinux2014-aarch64]
                  py2: ["35","36","37","38","39"]
      - name: Verify output
        run: |
          echo ${{ steps.test.outputs.matrix }}
          [ '${{ steps.test.outputs.matrix }}' == '{"include":[{"os":"macos-latest","component":"backend","dotnet":"4.7.2"},{"os":"macos-latest","component":"backend","dotnet":"5.0.102"},{"os":"macos-latest","component":"ui","dotnet":"4.7.2","node":"14.15.4"},{"os":"macos-latest","component":"ui","dotnet":"4.7.2","node":"15.6.0"},{"os":"macos-latest","component":"ui","dotnet":"5.0.102","node":"14.15.4"},{"os":"macos-latest","component":"ui","dotnet":"5.0.102","node":"15.6.0"},{"os":"ubuntu-latest","component":"backend","dotnet":"3.1.405"},{"os":"ubuntu-latest","component":"backend","dotnet":"5.0.102"},{"os":"ubuntu-latest","component":"ui","dotnet":"3.1.405","node":"14.15.4"},{"os":"ubuntu-latest","component":"ui","dotnet":"3.1.405","node":"15.6.0"},{"os":"ubuntu-latest","component":"ui","dotnet":"5.0.102","node":"14.15.4"},{"os":"ubuntu-latest","component":"ui","dotnet":"5.0.102","node":"15.6.0"},{"os":"windows-latest","component":"backend","dotnet":"3.1.405"},{"os":"windows-latest","component":"backend","dotnet":"5.0.102"},{"os":"windows-latest","component":"ui","dotnet":"3.1.405","node":"14.15.4"},{"os":"windows-latest","component":"ui","dotnet":"3.1.405","node":"15.6.0"},{"os":"windows-latest","component":"ui","dotnet":"4.7.2","node":"14.15.4"},{"os":"windows-latest","component":"ui","dotnet":"4.7.2","node":"15.6.0"},{"os":"windows-latest","component":"ui","dotnet":"5.0.102","node":"14.15.4"},{"os":"windows-latest","component":"ui","dotnet":"5.0.102","node":"15.6.0"}]}' ]
