name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test action
        uses: ./
        id: test
        with:
          config: |
            matrix:
              os: [ubuntu-latest, windows-latest]
              component: [backend, ui]
              dotnet: [3.1.405, 5.0.102]
            operations:
              - type: merge
                match: [component]
                matrix:
                  component: [ui]
                  node: [14.15.4, 15.6.0]
              - type: add
                match: [os, component]
                matrix:
                  os: [windows-latest]
                  component: [ui]
                  dotnet: [4.7.2]
              - type: add
                matrix:
                  os: [osx]
                  component: [backend,ui]
                  dotnet: [5.0.102,4.7.2]
      - name: Verify output
        run: |
          echo ${{ steps.test.outputs.matrix }}
